set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

set(EMSCRIPTEN_DEFAULT_SEARCH_PATH /usr/local)

if (NOT DEFINED EMSCRIPTEN_PATH)
	set(EMSCRIPTEN_PATH $ENV{EMSCRIPTEN_PATH})
endif()


if (NOT EXISTS ${EMSCRIPTEN_PATH})
	if (EXISTS ${EMSCRIPTEN_DEFAULT_SEARCH_PATH}/emcc)
		set (EMSCRIPTEN_PATH ${EMSCRIPTEN_DEFAULT_SEARCH_PATH})
	endif()
endif()


if (EXISTS ${EMSCRIPTEN_PATH}/emcc)
	set (EMSCRIPTEN_PATH ${EMSCRIPTEN_PATH} CACHE PATH "Path to emscripten binaries" FORCE)
endif()


set (CMAKE_C_COMPILER ${EMSCRIPTEN_PATH}/emcc CACHE PATH "gcc" FORCE)
set (CMAKE_CXX_COMPILER ${EMSCRIPTEN_PATH}/em++ CACHE PATH "g++" FORCE)
set (CMAKE_AR ${EMSCRIPTEN_PATH}/emar CACHE PATH "archive" FORCE)
set (CMAKE_LINKER ${EMSCRIPTEN_PATH}/emlink.py CACHE PATH "linker" FORCE)
set (CMAKE_RANLIB ${EMSCRIPTEN_PATH}/emranlib CACHE PATH "ranlib" FORCE)

set (EMSCRIPTEN True)
set (BUILD_EMSCRIPTEN True)

